steps:
  # Single step to merge to main branch
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '-X'
      - 'POST'
      - '-H'
      - 'Authorization: token ${_GITHUB_TOKEN}'
      - '-H'
      - 'Accept: application/vnd.github.v3+json'
      - 'https://api.github.com/repos/ygupta93/cypress-test/pulls'
      - '-d'
      - '{"title":"Your Pull Request Title","body":"Your Pull Request Description","head":"qa","base":"main"}'

options:
    logging: CLOUD_LOGGING_ONLY